### ISSUE TITLE
Event functionality

### ISSUE THREAD

**Issue by matthewkover** [matthewkover/botus-primus#10]
We have already started working on a fully functional event handling, storing and notification system. The issue addresses this.

**Comment by SparrowDivision** [comment]
Need to find out how to store event and other details in a hidden file on the server side.

**Comment by matthewkover** [comment]
We either try some sort of an easily implementable database e.g mongodb or find out a solution where we store the events within the node.js application (not sure if that is an option)

**Comment by matthewkover** [comment]
I separate this issue from any database related issue. See #11 for info.
